[build]
  functions = "netlify/functions"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  autoLaunch = false

[build.environment]
  NODE_VERSION = "14.x"
  NPM_VERSION = "7.x"

[build.bundledDependencies]
  - node-fetch
